---
version: "2.1"
name: "media-server"

services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    environment:
      - PUID=1000
      - PGID=1000
      # - VERSION=latest
      # - PLEX_CLAIM=optional
    volumes:
      - ./plex/plex:/config
      - ./plex/tv:/tv
      - ./plex/movies:/movies
      - ./plex/music:/music
      - ./plex/photos:/photos