---
version: "2.1"
services:
  # # gluetun:
  # #   image: qmcgaw/gluetun
  # #   # container_name: gluetun
  # #   # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
  # #   cap_add:
  # #     - NET_ADMIN
  # #   devices:
  # #     - /dev/net/tun:/dev/net/tun
  # #   ports:
  # #     - 8888:8888/tcp # HTTP proxy
  # #     - 8388:8388/tcp # Shadowsocks
  # #     - 8388:8388/udp # Shadowsocks
  # #   volumes:
  # #     - /yourpath:/gluetun
  # #   environment:
  # #     # See https://github.com/qdm12/gluetun/wiki
  # #     - VPN_SERVICE_PROVIDER=ivpn
  # #     - VPN_TYPE=openvpn
  # #     # OpenVPN:
  # #     - OPENVPN_USER=
  # #     - OPENVPN_PASSWORD=
  # #     # Wireguard:
  # #     # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
  # #     # - WIREGUARD_ADDRESSES=10.64.222.21/32
  # #     # Timezone for accurate log times
  # #     - TZ=
  # qbittorrent:
  #   image: linuxserver/qbittorrent
  #   container_name: qbittorrent
  #   environment:
  #     - PGID=1000
  #     - PUID=1000
  #     - UMASK=022
  #     - WEBUI_PORT=8080
  #   network_mode: "service:wireguard"
  #   restart: unless-stopped
  #   volumes:
  #     - ./qbittorrent:/config/qBittorrent/
  #     - ./qbittorrent/downloads:/downloads
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    environment:
      - PUID=1000
      - PGID=1000
      # - VERSION=latest
      # - PLEX_CLAIM=optional
    volumes:
      - ./plex/plex:/config
      - ./plex/tv:/tv
      - ./plex/movies:/movies
      - ./plex/music:/music
      - ./plex/photos:/photos