---
version: "2.1"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    environment:
      - PUID=1000
      - PGID=1000
      # - VERSION=latest
      # - PLEX_CLAIM=optional
    volumes:
      - ./plex:/config
      - ./tv:/tv
      - ./movies:/movies
      - ./music:/music
      - ./photos:/photos